### ISSUE TITLE
Step chart view

### ISSUE THREAD

**Issue by heavy-drinker** [jasonxunxu/dokuwiki-plugin-c3chart#10]
Hi, I'm trying to insert the 'step chart' into my dokuwiki page, but I have no idea how to center the ticks  and the 'middle' of each step as it's done in c3.js example (http://c3js.org/samples/chart_step.html). Now it's centered by the left side of step.

**Comment by jasonxunxu** [comment]
Could not reproduce with latest release v0.2.1.
