### ISSUE TITLE
Request add support for right to left languages.

### ISSUE THREAD

**Issue by SMSadegh19** [jasonxunxu/dokuwiki-plugin-c3chart#11]
Hello!
It seems the new version of C3 supports Right To Left Languages like Persian and Arabic. (Maybe this plugin needs an update in C3 Version)
But this plugin doesn't support Right To Left Languages. for example I wrote this:
`
<c3>
{
  data: {
    columns: [
      ['اکبر صلواتی', 0],
      ['اصغر رضایی', 23],
      ['فاطمه انوشیروانی', 4],
      ['هاجر محمدی اصل', 49],
    ],
    type : 'pie',
  }
}
</c3>
`
and output is:
![image](https://user-images.githubusercontent.com/45296858/134260438-68afc3d6-8cda-46be-b3a9-ea91952cc278.png)

The problem is about column names.

**Comment by SMSadegh19** [comment]
Hi! @jxai

**Comment by jxai** [comment]
Kindly send a pull request, I will review and merge. Thanks.
